/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'React 最佳实践',
      items: ['react-best-practices/practices'],
    },
    {
      type: 'category',
      label: 'Vue 最佳实践',
      items: ['vue-best-practices/practices'],
    },
    {
      type: 'category',
      label: 'Git 实践',
      items: ['git/experience'],
    },
    {
      type: 'category',
      label: 'Nodejs 实践',
      items: ['nodejs/problems'],
    },
    {
      type: 'category',
      label: 'Electron 实践',
      items: ['electron/experience'],
    },
    {
      type: 'category',
      label: '知识累积',
      items: ['knowledge/server-push'],
    },
    {
      type: 'category',
      label: '其它',
      items: ['other/problems'],
    },
  ],
};

module.exports = sidebars;
